### ISSUE TITLE
Different PDF adapters support

### ISSUE THREAD

**Issue by ishakhsuvarov** [magento-hackathon/Imagine2017#38] opened 2017-04-01 18:21 UTC
**Description**
Default PDF implementation in Magento is too hard to customize for extension developers, even changing default font requires substantial effort. It is proposed to add support for the `html2pdf` tool.

**Acceptance Criteria**
* PDF rendering middleware is implemented in Magento, to allow integration with different tools.
* Adapter for `html2pdf` is implemented.
* Implemented Solution is used in invoice, shipment and credit memo PDFs

**Comment by JosephLeedy** [comment] 2017-04-01 18:24
I think this is a duplicate of #3.

**Closed as completed** 2017-04-01 18:36 UTC
Labels: mage2, magento-engcom
